name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  # Frontend Code Quality
  frontend-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: Front-end/package-lock.json

      - name: Install Frontend dependencies
        run: npm ci
        working-directory: ./Front-end

      - name: Check Frontend code formatting
        run: npm run format:check
        working-directory: ./Front-end

      - name: Run Frontend ESLint
        run: npm run lint
        working-directory: ./Front-end

      - name: Run Frontend TypeScript check
        run: npx tsc --noEmit
        working-directory: ./Front-end

      - name: Run Frontend tests
        run: npm test
        working-directory: ./Front-end

      - name: Build Frontend application
        run: npm run build
        working-directory: ./Front-end

  # Admin Panel Code Quality (No Deployment)
  admin-panel-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: admin-panel/package-lock.json

      - name: Install Admin Panel dependencies
        run: npm ci
        working-directory: ./admin-panel

      - name: Check Admin Panel code formatting
        run: npm run format:check
        working-directory: ./admin-panel

      - name: Run Admin Panel ESLint
        run: npm run lint
        working-directory: ./admin-panel

      - name: Run Admin Panel TypeScript check
        run: npx tsc --noEmit
        working-directory: ./admin-panel

      - name: Run Admin Panel tests
        run: npm test
        working-directory: ./admin-panel

      - name: Build Admin Panel application
        run: npm run build
        working-directory: ./admin-panel

      - name: Admin Panel Security Audit
        run: npm audit --audit-level=moderate
        working-directory: ./admin-panel

  # Backend Code Quality (No Docker Deployment)
  backend-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: Back-end/package-lock.json

      - name: Install Backend dependencies
        run: npm ci
        working-directory: ./Back-end

      - name: Run Backend ESLint
        run: npm run lint
        working-directory: ./Back-end

      - name: Run Backend tests
        run: npm test
        working-directory: ./Back-end

      - name: Backend Security Audit
        run: npm audit --audit-level=moderate
        working-directory: ./Back-end

  # Deploy to Vercel (Frontend Only)
  deploy-frontend:
    runs-on: ubuntu-latest
    needs: [frontend-quality]
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci
        working-directory: ./Front-end

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./Front-end
          vercel-args: "--prod"
