name: Frontend CI/CD - Deploy to Vercel

on:
  push:
    branches: [main]
    paths:
      - 'Front-end/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    branches: [main]
    paths:
      - 'Front-end/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci
        working-directory: ./Front-end

      - name: Lint, Type Check, Build (optional)
        run: |
          npm run lint || true
          npm run format:check || true
          npx tsc --noEmit || true
        working-directory: ./Front-end

      - name: Deploy to Vercel (Recommended Stable Method)
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./Front-end
          vercel-args: '--prod'
